### ISSUE TITLE
После отметки задачи выполненной она все равно отображается в active

### ISSUE THREAD

**Issue by didolf** [buza94s/final-todo-list#1]
<img width="624" alt="Снимок экрана 2020-08-31 в 09 35 16" src="https://user-images.githubusercontent.com/33488113/91689676-48966580-eb6d-11ea-86a3-41873bbf4f05.png">

**Comment by didolf** [comment]
Есть чувство, что фильтрация не работает

**Comment by didolf** [comment]
Ага, у тебя работает клик и кружок отдельно, это по сути одно и то же.

**Comment by buza94s** [comment]
У меня был перевод в список выполненных задач при нажатии на текст. Сделал чтобы это работало по чекбоксу
